seed: 0
mem_frac: 0.5
n_epochs: 100
batch_size: 32
lr: 0.004 # 0.004
scheduler: True
alpha_cosine: 0
warmup_frac: 0.3
weight_decay: 0.01
n_layers: 3
hidden_dim: 20
# ENCODER
encoder: False
# SKIP
layer_skip: True
element_skip: False
# RECURRENT
enable_rec: True
rec_act: sigmoid
# CONVOLUTION
enable_conv: True
conv: 'dcls' # 'dcls', 'conv', ~
kernel_size: 64
init_std: 0.7
delay_type: 'dendritic' # 'synaptic', 'axonal', 'dendritic'
delay_kernel: 'gaussian'
wavenet_dilation: ~ # means LERF
dilation_schedule: ~ # 'clip', 'wrap', ~
dilation_offset: ~
constant_dilation: ~
kernel_n_elems: 1 # DCLS
heterogeneous_weights: False # DCLS
heterogeneous_positions: True # DCLS
heterogeneous_std: True # DCLS
train_weights: False # DCLS
train_positions: True
train_std: False
# CHANNEL MIXING
enable_cm: False
channel_mixing: 'mlp' # 'glu', 'mlp', ~
cm_act: 'relu' # 'relu', 'gelu', 'linear'
glu_type: ~ # 'full', 'candidate', 'gate'
# COMPRESSION
latent_dim: ~
comp_act: 'relu' # 'relu', 'gelu', 'linear'
# NORMALIZATION
postnorm: True
# REGULARIZATION
do_rate: 0
reg_factor: 0
# Wandb gradients
wandb_gradients: True
